site_name: RCAC HPC Exchange
site_url: "https://rcac-hpc-exchange.readthedocs.io/en/latest/"

nav:
  - Home: ./index.md
  - Learning Outcomes: ./learning-outcomes.md
  - Week 1:
      - Overview: week1/index.md
      - Setting up: week1/setup.md
      - Unix: week1/unix.md
      - The Shell: week1/shell.md
      - Commands: week1/commands.md
      - Navigating Filesystems: week1/filesystem.md
      - Editing Files: week1/editing.md
      - Access: week1/access.md
      - Command Reference: week1/reference.md
  - Week 2:
      - Overview: week2/index.md
      - What is a Cluster?: week2/what-is-a-cluster.md
      - Purdue Clusters: week2/clusters.md
      - Cluster Access: week2/access.md
      - File Storage and Transfer: week2/storage-transfer.md
      - Cluster Applications: week2/applications.md
      - Cluster Job Submission: week2/slurm-basics.md
  - Week 3:
      - Overview: week3/index.md
      - Scripting: week3/scripting.md
      - Managing processes: week3/processes.md
      - Pipes: week3/pipes.md
      - Files & directories: week3/files-directories.md
  - Week 4:
      - Overview: week4/index.md
      - Storage & transfers: week4/storage-transfer.md
      - Multinode & topology: week4/multinode-topology.md
      - Job history: week4/job-history.md
      - Utilization & monitoring: week4/utilization-monitoring.md
      - Workload management: week4/workload-management.md
  - Reference:
      - Cheatsheet: reference/command-cheatsheet.md
      - Glossary: reference/glossary.md
      - FAQ: reference/faq.md

    
theme:
  name: material
  # logo: assets/logo.png
  # favicon: assets/favicon.ico

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Merriweather Sans
    code: Red Hat Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition 
  - pymdownx.details
